---
title: "AN597_Week2"
author: "Christian Gagnon"
date: "9/11/2019"
output: html_document
---

hi!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Module 4


##Challenge 1
Input data into R
```{r}
u <- "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed."
u
```
Remove punctuation
```{r}
v <- gsub("[[:punct:]]","",u)
v
```
Split my string into substrings
```{r}
w <- strsplit(v," ")[[1]]
w
```

```{r}
z<-matrix(w, nrow = 22 , ncol = 1)
z
```
```{r}
z[c(3,6,9,12,15,18,21)]
```



##Challenge 2
```{r}
m <- matrix(data=1:80,nrow=8,ncol=10,byrow=FALSE,)
m
```

```{r}
x1<-m[1:8,2:3]
x1
x2<-m[1:8,6]
x2
x<-cbind(x1,x2)
x
```

```{r}
x<-m[6:8,1:9]
x
```

```{r}
m
x<-m[2:6,2:9]
x
```

##Challenge 3
```{r}
a<-array(data=400:1, dim=c(5,5,4,4))
a
```

```{r}
a[1, 1, 1, 2]
```

```{r}
a[2, 3, 2, ]
```

```{r}
a[1:5, 1:5, 3, 3]
```

#Challenge 4
```{r}
p<-list("Primates",
"Haplorhini",
"Anthropoidea",
"Platyrrhini",
"Cebidae",
"Atelidae",
"Pitheciidae",
"Catarrhini",
"Cercopithecidae",
"Hylobatidae",
"Hominidae",
"Tarsioidea",
"Tarsiidae",
"Strepsirhini",
"Lorisoidea",
"Lorisidae",
"Galagidae",
"Lemuroidea",
"Cheirogaleidae",
"Lepilemuridae",
"Indriidae",
"Lemuridae",
"Daubentoniidae")
p
```

```{r}
b<-matrix(c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2),nrow=5,ncol=3,byrow=TRUE)
b
```

```{r}
df <- data.frame(b)
df
```

```{r}
<-data.frame(V1 = as.numeric(1:5), V2 = as.numeric(1:5), V3 = as.factor(1:5), stringsAsFactors = FALSE)
as.logical(df$X2) 
as.factor(df$X3)
str(df)
```

